// -----
// !!!!!!!
// -------- DO NOT EDIT THIS FILE
// !!!!!!
// -----

const key = 'bio:orders';

/**
 * @param {Function} callback
 */
const getAll = (callback) => {
  setTimeout(() => {
    const shouldFail = Math.random() > 0.9;
    const data = window.localStorage.getItem(key);
    let orders = [];

    try {
      orders = JSON.parse(data) || [];
    } catch (e) {
      return callback(e);
    }

    callback(
      shouldFail ? new Error('Ooops, error!') : null,
      orders
    );
  }, 100);
};

/**
 * @param {Object} order
 * @param {Function} callback
 */
const save = (order, callback) => {
  const id = Math.random().toString(16).substr(2);

  getAll((err, orders) => {
    if (err) {
      return callback(err);
    }

    const data = JSON.stringify(orders.concat({...order, id}));
    window.localStorage.setItem(key, data);
    callback();
  });
};

const clear = (callback) => {
  setTimeout(() => {
    window.localStorage.clear();
    callback();
  });
};

export default {
  getAll,
  save,
  clear
};